version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname2
      - DB_USER=postgres
      - DB_PASSWORD=1234

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  redis:
    image: redis
    hostname: redis


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .

    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

#  frontend:
#    build:
#      context: ./frontend/
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    command: npm start
#    volumes:
#      - /frontend/node_modules
#
#    depends_on:
#      - backend
