version: '3'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./base:/base
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=postgres
      - DB_PASSWORD=1234

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

