# Generated by Django 4.1.5 on 2023-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='numbers',
            field=models.PositiveIntegerField(default=211),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='vocation',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Executor', 'Executor')], default='Customer', max_length=20),
        ),
    ]
