# Generated by Django 4.1.5 on 2023-01-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_numbers_client_vocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Developer', 'Developer'), ('Design', 'Design'), ('SMM', 'SMM'), ('Marketing', 'Marketing'), ('GameDev', 'GameDev')], default='GameDev', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('task_completed', models.CharField(choices=[('Task completed', 'Task completed'), ('Pending', 'Pending'), ('Looking for', 'Looking for')], default='Looking for', max_length=100)),
                ('dogovor_price', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_text', models.TextField()),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.executor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customerorder')),
            ],
        ),
    ]
